# Predicting the Price of Used Cars

In this Project, we are going to predict the Price of Used Cars using various features like Present_Price, Selling_Price, Kms_Driven, Fuel_Type, Year etc. 

To be able to predict used cars market value can help both buyers and sellers.

There are lots of individuals who are interested in the used car market at some points in their life because they wanted to sell their car or buy a used car. In this process, it’s a big corner to pay too much or sell less then it’s market value.

# Importing libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Loading the raw data

In [ ]:
df=pd.read_csv('clean2')
df.head(3)

# Preprocessing

Exploring the descriptive statistics of the variables

In [3]:
df1 = df.dropna()

In [4]:
df1.columns

Index(['Unnamed: 0', 'price', 'year', 'manufacturer', 'model', 'condition',
       'cylinders', 'fuel', 'odometer', 'title_status', 'transmission', 'VIN',
       'drive', 'type', 'paint_color', 'image_url', 'description', 'state',
       'lat', 'long', 'posting_date'],
      dtype='object')

In [5]:
df1.shape

(60631, 21)

In [6]:
df1['price'].unique()

array([27990, 34590, 29990, ..., 12589, 11589,  4790])

In [7]:
df1['year'].unique

<bound method Series.unique of 32        2012.0
33        2016.0
35        2016.0
36        2011.0
38        2017.0
           ...  
426859    2020.0
426860    2017.0
426866    2016.0
426874    2018.0
426878    2018.0
Name: year, Length: 60631, dtype: float64>

In [8]:
df1['year']=df1['year'].astype(object)

/tmp/ipykernel_7229/3034211116.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['year']=df1['year'].astype(object)


In [9]:
df1['manufacturer'].unique()

array(['gmc', 'chevrolet', 'jeep', 'nissan', 'ford', 'toyota', 'ram',
       'infiniti', 'chrysler', 'bmw', 'mazda', 'mercedes-benz', 'ferrari',
       'lexus', 'audi', 'mitsubishi', 'volkswagen', 'honda', 'hyundai',
       'fiat', 'kia', 'cadillac', 'rover', 'jaguar', 'lincoln', 'dodge',
       'volvo', 'acura', 'subaru', 'mini', 'buick', 'porsche',
       'alfa-romeo', 'saturn', 'tesla', 'harley-davidson', 'pontiac',
       'mercury', 'datsun', 'land rover', 'aston-martin'], dtype=object)

In [10]:
df1['model'].unique()

array(['sierra 2500 hd extended cab', 'silverado 1500 double',
       'colorado extended cab', ..., 'f150, xlt', 'f150, platinum',
       'cruze, 2lt'], dtype=object)

In [11]:
df1['condition'].unique()

array(['good', 'like new', 'excellent', 'fair', 'new', 'salvage'],
      dtype=object)

In [12]:
df1['cylinders'].unique()

array(['8 cylinders', '6 cylinders', '4 cylinders', '5 cylinders',
       '10 cylinders', '3 cylinders', 'other', '12 cylinders'],
      dtype=object)

In [13]:
df1 = df1[df1['cylinders']!="other"]

In [14]:
df1['cylinders']=df1['cylinders'].str.replace(" cylinders","").astype(int)

In [15]:
df1['fuel'].unique()

array(['gas', 'other', 'hybrid', 'diesel', 'electric'], dtype=object)

In [16]:
df1 = df1[df1['fuel']!="other"]

In [17]:
df1['odometer'].unique()

array([ 68696.,  29499.,  17302., ..., 176261., 172511.,  69550.])

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58777 entries, 32 to 426878
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    58777 non-null  int64  
 1   price         58777 non-null  int64  
 2   year          58777 non-null  object 
 3   manufacturer  58777 non-null  object 
 4   model         58777 non-null  object 
 5   condition     58777 non-null  object 
 6   cylinders     58777 non-null  int64  
 7   fuel          58777 non-null  object 
 8   odometer      58777 non-null  float64
 9   title_status  58777 non-null  object 
 10  transmission  58777 non-null  object 
 11  VIN           58777 non-null  object 
 12  drive         58777 non-null  object 
 13  type          58777 non-null  object 
 14  paint_color   58777 non-null  object 
 15  image_url     58777 non-null  object 
 16  description   58777 non-null  object 
 17  state         58777 non-null  object 
 18  lat           58777 non-null 

In [19]:
df1['odometer']=df1['odometer'].astype(int)

In [20]:
df1['title_status'].unique()

array(['clean', 'rebuilt', 'salvage', 'lien', 'missing', 'parts only'],
      dtype=object)

In [21]:
df1['transmission'].unique()

array(['other', 'automatic', 'manual'], dtype=object)

In [22]:
df1 = df1[df1['transmission']!="other"]

In [23]:
df1['type'].unique()

array(['van', 'sedan', 'truck', 'convertible', 'coupe', 'SUV',
       'hatchback', 'wagon', 'pickup', 'other', 'mini-van', 'offroad',
       'bus'], dtype=object)

In [24]:
df1 = df1[df1['type']!="other"]

In [25]:
df1['paint_color'].unique()

array(['white', 'silver', 'blue', 'red', 'grey', 'black', 'brown',
       'green', 'custom', 'yellow', 'orange', 'purple'], dtype=object)

In [26]:
df1['description'].unique()

array(['2018 Chevrolet Express Cargo Van RWD 2500 135"Clean Title with a Powerful and Reliable 4.3L Engine  Available for test drive at Moates Auto Xchange 334-445-1460  VIN: 1GCWGAFP8J1309579 Condition: UsedExterior: White Interior:  Mileage: 68,472 Transmission:Automatic Engine: 4.3L Stock# P2223   Features Included (5BV) Upfitter electrical or (PCH) Hotel Shuttle Package.)(5BV) Upfitter electrical provisions or (LWN) 2.8L Duramax Turbo-Diesel engine.)(5BV) Upfitter electrical provisions or (ZP6) 5-passenger Express Crew Van.)(9L7) Wiring junction block equipment accessory(C69) rear air conditioning105 amps (Not available with (Y3H) Paratransit Package298 lb-ft of torque [404 Nm] @ 3900 rpm) (Reference the Engine/Axle page for availability.)3 on the engine console cover3.42 ratio (Reference the Engine/Axle page for availability.)4-wheel antilock4-wheel disc4.3L V6 with Direct Injection and Variable Valve Timing60/40 split600 cold-cranking amps8600 lbs. (3901 kg) (Reference the Engine

In [27]:
df1['state'].unique()

array(['al', 'ak', 'az', 'ar', 'ca', 'co', 'ct', 'dc', 'de', 'fl', 'ga',
       'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky', 'la', 'me', 'md', 'ma',
       'mi', 'mn', 'ms', 'mo', 'mt', 'nc', 'ne', 'nv', 'nj', 'nm', 'ny',
       'nh', 'nd', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx',
       'ut', 'vt', 'va', 'wa', 'wv', 'wi', 'wy'], dtype=object)

In [28]:
df1['lat'].unique()

array([31.425091, 33.614088, 33.9135  , ..., 42.2655  , 41.326706,
       43.64293 ])

In [29]:
df1['long'].unique()

array([ -85.617723,  -85.796729,  -84.6859  , ..., -104.7512  ,
       -105.58651 , -108.222976])

In [30]:
df1['posting_date'].unique()

array(['2021-04-12T11:20:35-0500', '2021-04-12T11:20:00-0500',
       '2021-04-12T11:19:58-0500', ..., '2021-04-05T16:29:38-0600',
       '2021-04-05T15:18:42-0600', '2021-04-04T03:21:34-0600'],
      dtype=object)

In [31]:
df1 = df1[df1['price']!="other"]

In [32]:
df2 = df1.drop(['image_url', 'description','lat', 'long', 'posting_date','Unnamed: 0','VIN'],axis=1)
df2.head(2)

price    year manufacturer              model condition  cylinders fuel  \
126      0  2018.0    chevrolet  express cargo van  like new          6  gas   
127      0  2019.0    chevrolet  express cargo van  like new          6  gas   

     odometer title_status transmission drive type paint_color state  
126     68472        clean    automatic   rwd  van       white    al  
127     69125        clean    automatic   rwd  van       white    al

In [33]:
df2.shape

(47216, 14)

In [34]:
df2 = df2[df2['price']!=0]

In [35]:
df2.shape

(44349, 14)

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44349 entries, 215 to 426874
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   price         44349 non-null  int64 
 1   year          44349 non-null  object
 2   manufacturer  44349 non-null  object
 3   model         44349 non-null  object
 4   condition     44349 non-null  object
 5   cylinders     44349 non-null  int64 
 6   fuel          44349 non-null  object
 7   odometer      44349 non-null  int64 
 8   title_status  44349 non-null  object
 9   transmission  44349 non-null  object
 10  drive         44349 non-null  object
 11  type          44349 non-null  object
 12  paint_color   44349 non-null  object
 13  state         44349 non-null  object
dtypes: int64(3), object(11)
memory usage: 5.1+ MB


In [37]:
df2.describe()

price     cylinders      odometer
count   44349.000000  44349.000000  4.434900e+04
mean    16856.185325      5.857517  1.069482e+05
std     12859.537570      1.654989  1.032702e+05
min         1.000000      3.000000  0.000000e+00
25%      7880.000000      4.000000  6.512500e+04
50%     12995.000000      6.000000  1.036250e+05
75%     22987.000000      8.000000  1.401240e+05
max    155000.000000     12.000000  9.999999e+06

In [38]:
df2=df2[df2["odometer"]<4e5]

In [39]:
df2.describe()

price     cylinders       odometer
count   44295.000000  44295.000000   44295.000000
mean    16862.064070      5.856530  105419.773428
std     12862.814127      1.655211   55642.988364
min         1.000000      3.000000       0.000000
25%      7887.500000      4.000000   65100.000000
50%     12995.000000      6.000000  103540.000000
75%     22988.000000      8.000000  140000.000000
max    155000.000000     12.000000  372575.000000

In [40]:
df2=df2[df2["price"]>500]

In [41]:
df2['year']=df2['year'].astype(int)

In [42]:
df2["manufacturer"]

215              toyota
219                 bmw
268               mazda
337                ford
338       mercedes-benz
              ...      
426793        chevrolet
426800        chevrolet
426823    mercedes-benz
426833           jaguar
426874            lexus
Name: manufacturer, Length: 43805, dtype: object

In [43]:
df3 = df2["manufacturer"]

In [44]:
df3

215              toyota
219                 bmw
268               mazda
337                ford
338       mercedes-benz
              ...      
426793        chevrolet
426800        chevrolet
426823    mercedes-benz
426833           jaguar
426874            lexus
Name: manufacturer, Length: 43805, dtype: object

In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
label_encoder = LabelEncoder()
df3['Category_encoded'] = label_encoder.fit_transform(df3)

/tmp/ipykernel_7229/3265209535.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Category_encoded'] = label_encoder.fit_transform(df3)


In [47]:
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Mapping of Original Values to Encoded Values:")
print(mapping)

Mapping of Original Values to Encoded Values:
{'acura': 0, 'alfa-romeo': 1, 'aston-martin': 2, 'audi': 3, 'bmw': 4, 'buick': 5, 'cadillac': 6, 'chevrolet': 7, 'chrysler': 8, 'datsun': 9, 'dodge': 10, 'ferrari': 11, 'fiat': 12, 'ford': 13, 'gmc': 14, 'harley-davidson': 15, 'honda': 16, 'hyundai': 17, 'infiniti': 18, 'jaguar': 19, 'jeep': 20, 'kia': 21, 'land rover': 22, 'lexus': 23, 'lincoln': 24, 'mazda': 25, 'mercedes-benz': 26, 'mercury': 27, 'mini': 28, 'mitsubishi': 29, 'nissan': 30, 'pontiac': 31, 'porsche': 32, 'ram': 33, 'rover': 34, 'saturn': 35, 'subaru': 36, 'tesla': 37, 'toyota': 38, 'volkswagen': 39, 'volvo': 40}


In [48]:
df3 = df2["fuel"]

In [49]:
label_encoder = LabelEncoder()
df3['Category_encoded'] = label_encoder.fit_transform(df3)

/tmp/ipykernel_7229/3265209535.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Category_encoded'] = label_encoder.fit_transform(df3)


In [50]:
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Mapping of Original Values to Encoded Values:")
print(mapping)

Mapping of Original Values to Encoded Values:
{'diesel': 0, 'electric': 1, 'gas': 2, 'hybrid': 3}


In [51]:
df3 = df2["cylinders"]

In [52]:
label_encoder = LabelEncoder()
df3['Category_encoded'] = label_encoder.fit_transform(df3)

/tmp/ipykernel_7229/3265209535.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Category_encoded'] = label_encoder.fit_transform(df3)


In [53]:
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Mapping of Original Values to Encoded Values:")
print(mapping)

Mapping of Original Values to Encoded Values:
{3: 0, 4: 1, 5: 2, 6: 3, 8: 4, 10: 5, 12: 6}


In [54]:
df3 = df2["drive"]

In [55]:
label_encoder = LabelEncoder()
df3['Category_encoded'] = label_encoder.fit_transform(df3)

/tmp/ipykernel_7229/3265209535.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Category_encoded'] = label_encoder.fit_transform(df3)


In [56]:
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Mapping of Original Values to Encoded Values:")
print(mapping)

Mapping of Original Values to Encoded Values:
{'4wd': 0, 'fwd': 1, 'rwd': 2}


In [ ]:
df3 = df2["year"]

In [ ]:
label_encoder = LabelEncoder()
df3['Category_encoded'] = label_encoder.fit_transform(df3)

In [ ]:
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Mapping of Original Values to Encoded Values:")
print(mapping)

In [ ]:
df3 = df2["drive"]

In [ ]:
label_encoder = LabelEncoder()
df3['Category_encoded'] = label_encoder.fit_transform(df3)

In [ ]:
mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Mapping of Original Values to Encoded Values:")
print(mapping)

In [57]:
df2.to_csv('cl_final2.csv')

# Deal with Object Value

In [42]:
from sklearn.preprocessing import LabelEncoder

# encoder = LabelEncoder()
# encoder.fit(df2["year"])
# df2["year"] = encoder.transform(df2["year"])

encoder = LabelEncoder()
encoder.fit(df2["manufacturer"])
df2["manufacturer"] = encoder.transform(df2["manufacturer"])

encoder = LabelEncoder()
encoder.fit(df2["model"])
df2["model"] = encoder.transform(df2["model"])

encoder = LabelEncoder()
encoder.fit(df2["condition"])
df2["condition"] = encoder.transform(df2["condition"])

encoder = LabelEncoder()
encoder.fit(df2["fuel"])
df2["fuel"] = encoder.transform(df2["fuel"])

encoder = LabelEncoder()
encoder.fit(df2["title_status"])
df2["title_status"] = encoder.transform(df2["title_status"])


encoder = LabelEncoder()
encoder.fit(df2["transmission"])
df2["transmission"] = encoder.transform(df2["transmission"])


encoder = LabelEncoder()
encoder.fit(df2["drive"])
df2["drive"] = encoder.transform(df2["drive"])


encoder = LabelEncoder()
encoder.fit(df2["type"])
df2["type"] = encoder.transform(df2["type"])


encoder = LabelEncoder()
encoder.fit(df2["paint_color"])
df2["paint_color"] = encoder.transform(df2["paint_color"])


encoder = LabelEncoder()
encoder.fit(df2["state"])
df2["state"] = encoder.transform(df2["state"])



In [43]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43805 entries, 215 to 426874
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         43805 non-null  int64
 1   year          43805 non-null  int64
 2   manufacturer  43805 non-null  int64
 3   model         43805 non-null  int64
 4   condition     43805 non-null  int64
 5   cylinders     43805 non-null  int64
 6   fuel          43805 non-null  int64
 7   odometer      43805 non-null  int64
 8   title_status  43805 non-null  int64
 9   transmission  43805 non-null  int64
 10  drive         43805 non-null  int64
 11  type          43805 non-null  int64
 12  paint_color   43805 non-null  int64
 13  state         43805 non-null  int64
dtypes: int64(14)
memory usage: 5.0 MB


In [47]:
df2["manufacturer"].unique()

array([38,  4, 25, 13, 26, 11, 23,  7,  3, 29, 18, 30, 39, 16, 33, 17, 12,
       21,  6, 34, 20, 14, 19, 40, 10,  8,  0, 36, 24, 28,  5, 32,  1, 35,
       37, 15, 31, 27,  9, 22,  2])

In [44]:
df2.corr()

price      year  manufacturer     model  condition  \
price         1.000000  0.353851     -0.083821  0.068560   0.062166   
year          0.353851  1.000000      0.004064  0.042873   0.012532   
manufacturer -0.083821  0.004064      1.000000 -0.010592  -0.032702   
model         0.068560  0.042873     -0.010592  1.000000  -0.011137   
condition     0.062166  0.012532     -0.032702 -0.011137   1.000000   
cylinders     0.394160 -0.173149     -0.262763  0.103177   0.045108   
fuel         -0.386167 -0.017645      0.049992 -0.016818  -0.012868   
odometer     -0.472241 -0.334364      0.030768  0.022232  -0.062668   
title_status -0.032489  0.041421      0.017385 -0.029639   0.021007   
transmission -0.030578 -0.197101      0.050893 -0.011642   0.012446   
drive        -0.142508 -0.173947     -0.070904 -0.128113   0.080360   
type          0.093661  0.040395     -0.017819 -0.086639   0.078017   
paint_color   0.067002  0.010379     -0.021697  0.012281   0.041377   
state        -0.010335  0.001858     -0.007384  0.045733   0.015615   

              cylinders      fuel  odometer  title_status  transmission  \
price          0.394160 -0.386167 -0.472241     -0.032489     -0.030578   
year          -0.173149 -0.017645 -0.334364      0.041421     -0.197101   
manufacturer  -0.262763  0.049992  0.030768      0.017385      0.050893   
model          0.103177 -0.016818  0.022232     -0.029639     -0.011642   
condition      0.045108 -0.012868 -0.062668      0.021007      0.012446   
cylinders      1.000000 -0.232867  0.106551     -0.055008     -0.085924   
fuel          -0.232867  1.000000 -0.065324      0.004242      0.003253   
odometer       0.106551 -0.065324  1.000000     -0.085227     -0.009799   
title_status  -0.055008  0.004242 -0.085227      1.000000     -0.002462   
transmission  -0.085924  0.003253 -0.009799     -0.002462      1.000000   
drive         -0.015956  0.097668 -0.079044     -0.020818      0.079750   
type           0.108155 -0.192459 -0.002970     -0.018183     -0.028500   
paint_color    0.088770 -0.086970 -0.001048     -0.036344     -0.018609   
state          0.017556 -0.031760  0.035183      0.003480      0.012289   

                 drive      type  paint_color     state  
price        -0.142508  0.093661     0.067002 -0.010335  
year         -0.173947  0.040395     0.010379  0.001858  
manufacturer -0.070904 -0.017819    -0.021697 -0.007384  
model        -0.128113 -0.086639     0.012281  0.045733  
condition     0.080360  0.078017     0.041377  0.015615  
cylinders    -0.015956  0.108155     0.088770  0.017556  
fuel          0.097668 -0.192459    -0.086970 -0.031760  
odometer     -0.079044 -0.002970    -0.001048  0.035183  
title_status -0.020818 -0.018183    -0.036344  0.003480  
transmission  0.079750 -0.028500    -0.018609  0.012289  
drive         1.000000  0.180020     0.110170 -0.072565  
type          0.180020  1.000000     0.096245  0.004151  
paint_color   0.110170  0.096245     1.000000 -0.001303  
state        -0.072565  0.004151    -0.001303  1.000000

# Final Clean CSV File

In [45]:
df2.to_csv('cl_final1')